#!/bin/bash

cat << EOF0 > ${DIRRUN}/initatmos.bash 
#!/bin/bash -x
#PBS -N ${INITATMOS_jobname}
#PBS -l select=${INITATMOS_nnodes}:ncpus=${INITATMOS_ncores}:mpiprocs=${INITATMOS_ncores}
#PBS -l walltime=${STATIC_walltime}
#PBS -q ${INITATMOS_QUEUE}
#PBS -o ${DATAOUT}/${YYYYMMDDHHi}/Pre/logs/initatmos.bash.o$PBS_JOBID          # File name for standard output
#PBS -e ${DATAOUT}/${YYYYMMDDHHi}/Pre/logs/initatmos.bash.e$PBS_JOBID          # File name for standard error output
#PBS -l place=excl
##PBS -l mem=500000mb


export executable=init_atmosphere_model

ulimit -c unlimited
ulimit -v unlimited
ulimit -s unlimited


. ${SCRIPTS}/setenv.bash

cd ${DIRRUN}



date
time mpirun -np \${SLURM_NTASKS} ./\${executable}
date


mv ${DIRRUN}/log.init_atmosphere.0000.out ${DATAOUT}/${YYYYMMDDHHi}/Pre/logs/log.init_atmosphere.0000.x1.${RES}.init.nc.${YYYYMMDDHHi}.out
mv ${DIRRUN}/namelist.init_atmosphere ${DATAOUT}/${YYYYMMDDHHi}/Pre/logs
mv ${DIRRUN}/streams.init_atmosphere ${DATAOUT}/${YYYYMMDDHHi}/Pre/logs
mv ${DIRRUN}/x1.${RES}.init.nc ${DATAOUT}/${YYYYMMDDHHi}/Pre

EOF0
