#!/bin/bash

cat << EOF0 > ${DIRRUN}/static.bash
#!/bin/bash -x
#PBS -N ${STATIC_jobname}
#PBS -l select=${STATIC_nnodes}:ncpus=${STATIC_ncpn}
#PBS -q ${STATIC_QUEUE}
#PBS -l walltime=${STATIC_walltime}
#PBS -o ${DATAOUT}/logs/static.bash.o$PBS_JOBID          # File name for standard output
#PBS -e ${DATAOUT}/logs/static.bash.e$PBS_JOBID          # File name for standard error output
#PBS -l place=excl
##PBS -l mem=500000mb


export executable=init_atmosphere_model

ulimit -s unlimited
ulimit -c unlimited
ulimit -v unlimited

. ${SCRIPTS}/setenv.bash

cd ${DIRRUN}

date
time mpirun -np \${SLURM_NTASKS} ./\${executable}
date

grep "Finished running" log.init_atmosphere.0000.out >& /dev/null
if [ \$? -ne 0 ]; then
   echo "  BUMMER: Static generation failed for some yet unknown reason."
   echo " "
   tail -10 ${STATICPATH}/log.init_atmosphere.0000.out
   echo " "
   exit 21
fi

echo "  ####################################"
echo "  ### Static completed - \$(date) ####"
echo "  ####################################"
echo " "


mv log.init_atmosphere.0000.out ${DATAOUT}/logs/log.init_atmosphere.0000.x1.${RES}.static.nc.out


EOF0
